/* eslint-disable react/no-unescaped-entities */
import { Banknote, CheckCircle2, Clock3, FileText } from "lucide-react";
import { requireUser } from "@/lib/authorization";
import { prisma } from "@/lib/prisma";
import { money } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
export const dynamic = "force-dynamic";
export default async function DashboardPage() { const session = await requireUser(); const role = session.user.role; const where = role === "ADMIN" ? {} : role === "EXPERT" ? { expertId: session.user.id } : { clientId: session.user.id }; const requests = await prisma.serviceRequest.findMany({ where, include: { payments: true }, orderBy: { createdAt: "desc" }, take: 8 }); const total = requests.reduce((sum, r) => sum + Number(r.total), 0); const paid = requests.flatMap((r) => r.payments).filter((p) => p.status === "PAID").reduce((sum, p) => sum + Number(p.amount), 0); const cards = [{ label: "Demandes", value: requests.length, icon: FileText }, { label: "En cours", value: requests.filter((r) => !["COMPLETED", "CANCELLED"].includes(r.status)).length, icon: Clock3 }, { label: "Terminées", value: requests.filter((r) => r.status === "COMPLETED").length, icon: CheckCircle2 }, { label: role === "CLIENT" ? "Montant engagé" : "Chiffre suivi", value: money(role === "CLIENT" ? total : paid), icon: Banknote }]; return <div><p className="text-sm font-semibold text-teal-700">Bonjour {session.user.name.split(" ")[0]}</p><h1 className="mt-1 text-3xl font-black">Vue d'ensemble</h1><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ icon: Icon, ...card }) => <Card key={card.label}><CardContent className="flex items-center justify-between pt-6"><div><p className="text-sm text-slate-500">{card.label}</p><p className="mt-2 text-2xl font-black">{card.value}</p></div><span className="grid size-11 place-items-center rounded-2xl bg-teal-50 text-teal-700"><Icon size={20} /></span></CardContent></Card>)}</div><Card className="mt-8"><CardHeader><CardTitle>Demandes récentes</CardTitle></CardHeader><CardContent>{requests.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-400"><tr><th className="py-3">Client</th><th>Service</th><th>Date</th><th>Montant</th><th>Statut</th></tr></thead><tbody>{requests.map((r) => <tr key={r.id} className="border-b last:border-0"><td className="py-4 font-medium">{r.customerName}</td><td>{r.kind}</td><td>{r.createdAt.toLocaleDateString("fr-DZ")}</td><td>{money(r.total)}</td><td><Badge>{r.status}</Badge></td></tr>)}</tbody></table></div> : <p className="py-10 text-center text-slate-500">Aucune demande pour le moment.</p>}</CardContent></Card></div>; }
